version: "3"

services:
  web:
    container_name: tweeter
    restart: always
    build: .
    ports:
      - "3001:3001"
    networks:
      - some-net
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  mongo:
    container_name: mongo
    image: mongo
    networks:
      - some-net
    ports:
      - "27017:27017"

networks:
  some-net:
    driver: bridge

volumes:
  exclude:
