version: "3"

services:
  web:
    container_name: tweeter
    restart: always
    build: .
    ports:
      - "5000:3000"
    networks:
      - some-net
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongo
    image: mongo
    networks:
      - some-net
    ports:
      - "27017:27017"

networks:
  some-net:
    driver: bridge
